import localFont from "next/font/local";
import { Montserrat } from 'next/font/google';
import { Krona_One } from "next/font/google";
import "./globals.css";
import "./customCss.css"

import { ClerkProvider } from "@clerk/nextjs";
import { CartProvider } from "@/Context/Context";
import ProgressBarProvider from "@/components/utils/ProgressBarProvider";

import BackgroundSync from "@/components/BackgroundSync";
// import loading from "./loading";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const getMonts = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat',
})

const getKrona = Krona_One({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-kron',
  weight: '400'
})



export const metadata = {
  title: "Faxx",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${getMonts.variable} ${getKrona.variable} antialiased`}
          >
            <CartProvider>
            <ProgressBarProvider>

              {children}
           
          </ProgressBarProvider>
              <BackgroundSync />
            </CartProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}