import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { ClerkProvider } from "@clerk/nextjs";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});



export const metadata = {
  title: "Faxx",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
     <div className="bg-slate-100 w-full z-[100] px-2 md:px-6 lg:px-10 xl:px-20 2xl:px-48 fixed top-0 left-0">
        <NavBar/>
      </div>
      <main className="mt-12 md:mt-14">
        {children}

      </main>
      </body>
    </html>
    </ClerkProvider>
  );
}
